import {
  ReservationStatus,
  ReservationType,
} from '../../../modules/reservations/entities/reservation.entity';
import type { ItineraryPlan } from '../../../modules/itineraries/itinerary-planner.port';

/**
 * Trip history for the demo tourist (kofi@voyago.test), so My Trips, Bookings
 * and Profile render with content instead of empty states.
 */

/**
 * The reservation's `item` snapshot needs the underlying row's uuid, which only
 * exists at seed time. `lookup` tells seed.ts which row to resolve: a stay or
 * restaurant slug, or an origin-destination pair for a generated flight.
 */
export interface SeedReservation {
  reference: string;
  type: ReservationType;
  status: ReservationStatus;
  totalMinor: number;
  lookup: string;
  title: string;
  subtitle: string;
  /** Relative to seed time; negative is in the past. */
  startsAtDaysFromNow: number;
  endsAtDaysFromNow: number;
}

export const seedReservations: SeedReservation[] = [
  {
    reference: 'RSV-2026-4101',
    type: ReservationType.STAY,
    status: ReservationStatus.COMPLETED,
    totalMinor: 360000,
    lookup: 'labadi-beach-hotel',
    title: 'Labadi Beach Hotel',
    subtitle: 'Deluxe Room · 3 nights',
    startsAtDaysFromNow: -45,
    endsAtDaysFromNow: -42,
  },
  {
    reference: 'RSV-2026-4102',
    type: ReservationType.STAY,
    status: ReservationStatus.CONFIRMED,
    totalMinor: 176000,
    lookup: 'aqua-safari-ada',
    title: 'Aqua Safari Resort',
    subtitle: 'Standard Room · 2 nights',
    startsAtDaysFromNow: 21,
    endsAtDaysFromNow: 23,
  },
  {
    reference: 'RSV-2026-4103',
    type: ReservationType.FLIGHT,
    status: ReservationStatus.COMPLETED,
    totalMinor: 85000,
    lookup: 'ACC-LOS',
    title: 'Accra → Lagos',
    subtitle: 'Africa World Airlines · Economy',
    startsAtDaysFromNow: -30,
    endsAtDaysFromNow: -30,
  },
  {
    reference: 'RSV-2026-4104',
    type: ReservationType.FLIGHT,
    status: ReservationStatus.CONFIRMED,
    totalMinor: 45000,
    lookup: 'ACC-KMS',
    title: 'Accra → Kumasi',
    subtitle: 'Africa World Airlines · Economy',
    startsAtDaysFromNow: 12,
    endsAtDaysFromNow: 12,
  },
  {
    reference: 'RSV-2026-4105',
    type: ReservationType.TABLE,
    status: ReservationStatus.COMPLETED,
    totalMinor: 19000,
    lookup: 'republic-bar-accra',
    title: 'Republic Bar & Grill',
    subtitle: 'Table for 2 · 19:30',
    startsAtDaysFromNow: -14,
    endsAtDaysFromNow: -14,
  },
  {
    reference: 'RSV-2026-4106',
    type: ReservationType.TABLE,
    status: ReservationStatus.CANCELLED,
    totalMinor: 38000,
    lookup: 'azmera-accra',
    title: 'Azmera',
    subtitle: 'Table for 2 · 20:00',
    startsAtDaysFromNow: 5,
    endsAtDaysFromNow: 5,
  },
];

export interface SeedItinerary {
  title: string;
  destinationName: string;
  days: number;
  budgetMinor: number;
  partySize: number;
  interests: string[];
  plan: ItineraryPlan;
}

/**
 * Hand-written plans. `model` is set to 'seed' by the orchestrator rather than a
 * real model id, so nothing here claims to have been generated by an LLM.
 */
export const seedItineraries: SeedItinerary[] = [
  {
    title: 'Three Days on the Cape Coast',
    destinationName: 'Cape Coast',
    days: 3,
    budgetMinor: 250000,
    partySize: 2,
    interests: ['history', 'nature'],
    plan: {
      summary:
        'Castles, rainforest canopy and the Elmina harbour over three days on the Central Region coast.',
      estimatedTotalMinor: 214000,
      notes: [
        'Book the Kakum canopy walk for the first morning slot to avoid the crowds.',
        'The castle tours are emotionally heavy — leave the afternoon after each one unscheduled.',
      ],
      days: [
        {
          day: 1,
          title: 'Arrival and Cape Coast Castle',
          items: [
            {
              period: 'morning',
              kind: 'FREE',
              title: 'Drive from Accra',
              description:
                'Roughly three hours along the coast road. Stop at Winneba if you want to break the journey.',
              bookable: false,
            },
            {
              period: 'afternoon',
              kind: 'TOUR',
              title: 'Cape Coast Castle Heritage Tour',
              description:
                'Guided tour of the dungeons, the Door of No Return and the upstairs museum.',
              tourSlug: 'cape-coast-castle-tour',
              estimatedCostMinor: 8000,
              bookable: true,
            },
            {
              period: 'evening',
              kind: 'MEAL',
              title: 'Dinner at Oasis Beach Restaurant',
              description:
                'Grilled barracuda on the beach beside the castle. Drumming most nights.',
              estimatedCostMinor: 11000,
              bookable: false,
            },
          ],
        },
        {
          day: 2,
          title: 'Kakum National Park',
          items: [
            {
              period: 'morning',
              kind: 'TOUR',
              title: 'Kakum Canopy Walk',
              description:
                'Seven rope bridges strung 30 metres above the rainforest floor.',
              tourSlug: 'kakum-canopy-walk',
              estimatedCostMinor: 12000,
              bookable: true,
            },
            {
              period: 'afternoon',
              kind: 'FREE',
              title: 'Rest at the hotel',
              description:
                'The canopy walk is more tiring than it looks in the humidity.',
              bookable: false,
            },
            {
              period: 'evening',
              kind: 'MEAL',
              title: 'Dinner at Baobab House',
              description:
                'Vegetarian cafe run as a social enterprise in Cape Coast town.',
              estimatedCostMinor: 5500,
              bookable: false,
            },
          ],
        },
        {
          day: 3,
          title: 'Elmina and the drive back',
          items: [
            {
              period: 'morning',
              kind: 'TOUR',
              title: 'Elmina Castle Guided Tour',
              description:
                'The oldest European building in sub-Saharan Africa, above the fishing harbour.',
              tourSlug: 'elmina-castle-tour',
              estimatedCostMinor: 8500,
              bookable: true,
            },
            {
              period: 'afternoon',
              kind: 'TIP',
              title: 'Leave by 15:00',
              description:
                'Traffic into Accra builds sharply from late afternoon on the N1.',
              bookable: false,
            },
          ],
        },
      ],
    },
  },
  {
    title: 'A Weekend in Kumasi',
    destinationName: 'Kumasi',
    days: 2,
    budgetMinor: 150000,
    partySize: 1,
    interests: ['culture', 'markets'],
    plan: {
      summary:
        'Ashanti royal history, the largest market in West Africa, and kente weaving at Bonwire.',
      estimatedTotalMinor: 96000,
      notes: [
        'Dress modestly for Manhyia Palace — it is an active royal residence.',
        'Kejetia is overwhelming without a guide. Go with one.',
      ],
      days: [
        {
          day: 1,
          title: 'Royal Kumasi',
          items: [
            {
              period: 'morning',
              kind: 'TOUR',
              title: 'Manhyia Palace Museum Tour',
              description:
                'The seat of the Asantehene, with regalia and the history of the Golden Stool.',
              tourSlug: 'manhyia-palace-tour',
              estimatedCostMinor: 9000,
              bookable: true,
            },
            {
              period: 'afternoon',
              kind: 'TOUR',
              title: 'Kejetia Market Walk',
              description: 'Navigate the market with a trader who works there.',
              tourSlug: 'kejetia-market-walk',
              estimatedCostMinor: 7000,
              bookable: true,
            },
            {
              period: 'evening',
              kind: 'MEAL',
              title: "Dinner at Vic Baboo's Cafe",
              description:
                'Central, cheap and reliable, with a menu that runs to several pages.',
              estimatedCostMinor: 6500,
              bookable: false,
            },
          ],
        },
        {
          day: 2,
          title: 'Bonwire and departure',
          items: [
            {
              period: 'morning',
              kind: 'TOUR',
              title: 'Bonwire Kente Weaving Workshop',
              description:
                'Learn the loom in the Ashanti kente village and take home the strip you weave.',
              tourSlug: 'bonwire-kente-workshop',
              estimatedCostMinor: 13500,
              bookable: true,
            },
            {
              period: 'afternoon',
              kind: 'FREE',
              title: 'Fly or drive back',
              description:
                'The Accra flight is under an hour; the road is four to five.',
              bookable: false,
            },
          ],
        },
      ],
    },
  },
];

export const seedEmergencyContacts = [
  {
    name: 'Akosua Mensah',
    phone: '+233244000101',
    email: 'akosua.mensah@example.com',
    relationship: 'Sister',
  },
  {
    name: 'Samuel Mensah',
    phone: '+233244000102',
    email: 'samuel.mensah@example.com',
    relationship: 'Father',
  },
  {
    name: 'Dr. Nana Adjei',
    phone: '+233244000103',
    relationship: 'Family doctor',
  },
];
